# base image - node:alpine
FROM node:18.20.2-bullseye-slim as base

# set the working directory to /app
WORKDIR /app

# copy contents
COPY frontend/public /app/public
COPY frontend/src /app/src
COPY frontend/.env /app/
COPY frontend/package.json /app/

# Run npm
RUN npm install

# start
CMD ["npm", "start"]

