apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.prod.yml
    kompose.version: 1.33.0 (3ce457399)
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert -f docker-compose.prod.yml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/project-w4-default: "true"
        io.kompose.service: server
    spec:
      containers:
        - image: europe-west10-docker.pkg.dev/concrete-racer-274913/aic-repo/server:latest
          name: server
          ports:
            - containerPort: 3000
              protocol: TCP
      restartPolicy: Always
